# Root Hydra configuration for edge model training

defaults:
  - model: atcn
  - data: sided
  - experiment: baseline
  - _self_

# Global settings
seed: 42
output_dir: outputs/nilm_model_artifacts/${now:%Y%m%d-%H%M%S}

model:
  learning_rate: 1e-4

# Data
data:
  window_size: 288
  batch_size: 256
  num_workers: 4
  use_amda: false
  amda_scale: 2.5
  stride: 5


# Training
training:
  max_epochs: 25
  patience: 10
  accelerator: auto
  devices: auto
  precision: "32"
  gradient_clip_val: 1.0
  stride: 5
  check_val_every_n_epoch: 2
  window_size:  288
  batch_size: 256
  num_workers: 4

# Logging
logging:
  use_wandb: false
  wandb_offline: false
  use_mlflow: false
  mlflow_tracking_uri: null
  mlflow_experiment_name: underscore-edge-model-pipeline
  mlflow_run_name: null
  project_name: underscore-edge-model-pipeline
  log_every_n_steps: 40

# Hydra configuration
hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: outputs/sweeps/${now:%Y-%m-%d}
    subdir: ${hydra.job.num}
